name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r master/venv_requirements.txt
          python -m pip install master/

      - name: lint with flake8
        run: |
          # Ignore star imports (F403/5),
          # indents before/after binary operators (W503/4),
          # invalid escape charaters (W605).
          flake8 master/examples/**/*.py master/nmrespy/**/*.py master/tests/*.py master/setup.py --ignore F403,F405,W503,W504,W605 --per-file-ignores="master/nmrespy/__init__.py:F401,master/nmrespy/load/__init__.py:F401,master/setup.py:F821"

      - name: test with pytest
        run: |
          cd master/tests/
          sed -i 's/VIEW_PEAKS = True/VIEW_PEAKS = False/g' test_plot.py
          sed -i 's/VIEW_RESULT_PLOTS = True/VIEW_RESULT_PLOTS = False/g' test_plot.py
          sed -i 's/VIEW_DATA = True/VIEW_DATA = False/g' test_estimator.py
          sed -i 's/VIEW_RESULT_FILES = True/VIEW_RESULT_FILES = False/g' test_estimator.py
          sed -i 's/VIEW_RESULT_FIGURES = True/VIEW_RESULT_FIGURES = False/g' test_estimator.py
          sed -i 's/RUN_PDFLATEX = True/RUN_PDFLATEX = False/g' test_estimator.py
          sed -i 's/MANUAL_PHASE = True/MANUAL_PHASE = False/g' test_estimator.py
          sed -i 's/USER_INPUT = True/USER_INPUT = False/g' test_write.py
          sed -i 's/MANUAL_PHASE = True/MANUAL_PHASE = False/g' test_sig.py
          python -m pytest
